nodeLinker: node-modules

npmAuthToken: '${NPM_TOKEN:-}'

npmPublishRegistry: 'https://registry.npmjs.org'

# Fix: ts-node-dev doesn't provide @types/node to ts-node
packageExtensions:
  'ts-node-dev@*':
    dependencies:
      '@types/node': '*'
