packages:
  - packages/*
  - packages/plugins/*
  - packages/client/*
  - packages/event-target/*
  - packages/envelop/*
  - packages/envelop/plugins/*
  - examples/**/*
  - '!examples/bun'
  - '!examples/bun-yoga-ws'
  - '!examples/deno'
  - '!examples/gcp-cloud-run'
  - '!examples/gcp-functions'
  - '!examples/firebase/*'
  - '!examples/**/dist'
  - '!packages/**/dist'
  - benchmark
  - benchmark/envelop
  - website
  - e2e
allowBuilds:
  '@apollo/protobufjs': true
  '@contrast/fn-inspect': false
  '@firebase/util': true
  '@nestjs/core': true
  '@newrelic/native-metrics': false
  '@parcel/watcher': true
  '@playwright/browser-chromium': false
  '@prisma/client': true
  '@prisma/engines': true
  '@pulumi/docker': true
  '@pulumi/docker-build': true
  '@sveltejs/kit': true
  '@swc/core': true
  aws-sdk: true
  bun: true
  egg-bin: true
  esbuild: true
  netlify-cli: true
  postinstall-postinstall: true
  prisma: true
  protobufjs: true
  sharp: true
  svelte-preprocess: true
  type-graphql: true
  unix-dgram: false
  unrs-resolver: true
  workerd: true
patchedDependencies:
  '@changesets/assemble-release-plan@6.0.10': patches/@changesets__assemble-release-plan@6.0.10.patch
  jest-leak-detector: patches/jest-leak-detector.patch
  package-up: patches/package-up.patch
  jest-environment-node: patches/jest-environment-node.patch
  '@miniflare/core': patches/@miniflare__core.patch
  minimatch: patches/minimatch.patch
  bob-the-bundler: patches/bob-the-bundler.patch
overrides:
  '@isaacs/brace-expansion': ^5.0.1
  brace-expansion: ^5.0.5
  minimatch: ^10.2.3
  axios: ^1.13.5
  fastify: ^5.8.1
  lodash: ^4.17.23
  lodash-es: ^4.17.23
  markdown-it: ^14.1.1
  body-parser: ^2.2.1
  estree-util-value-to-estree: ^3.5.0
  eslint-plugin-unicorn: ^56.0.1
  esbuild: ^0.27.0
  cookie: ^1.0.2
  graphql: 16.13.2
  handlebars: ^4.7.9
  file-type: ^21.3.2
  flatted: ^3.4.0
  glob: ^11.1.0
  koa: ^3.1.2
  node-forge: ^1.4.0
  '@changesets/assemble-release-plan': ^6.0.10
  '@types/react': ^19.2.4
  '@xmldom/xmldom': 0.9.9
  multer: ^2.1.1
  on-headers: ^1.1.0
  tar: ^7.5.11
  tmp: ^0.2.5
  qs: ^6.14.2
  validator: ^13.15.22
  jws: ^3.2.3
  mdast-util-to-hast: ^13.2.1
  h3: ^1.15.5
  undici: ^7.24.0
  preact: ^10.27.3
  js-yaml: ^3.14.2
  diff: ^8.0.3
  '@apollo/composition': ^2.12.1
  webpack: ^5.104.1
  rollup: ^4.59.0
  picomatch: ^4.0.4
  path-to-regexp: ^8.4.0
  serialize-javascript: ^7.0.5
  socket.io-parser: ^4.2.6
  fast-xml-parser: ^5.3.8
  '@sveltejs/kit': ^2.53.3
