name: Website Integrity
on:
  pull_request:
    paths:
      - 'website/**'
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  website-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Fetch
        run: git fetch origin main

      - name: Setup env
        uses: the-guild-org/shared-config/setup@v1
        with:
          node-version-file: .node-version

      - name: Build Packages
        run: pnpm build

      - name: Typecheck
        run: pnpm --filter website run build

      - name: Compare
        run: git diff origin/${{ github.base_ref }}.. -- website/route-lockfile.txt

      - name: Diff to file
        if: always()
        id: diff_result
        run: |
          OUTPUT=$(git diff origin/${{ github.base_ref }}.. -- website/route-lockfile.txt)
          OUTPUT="${OUTPUT//'%'/'%25'}"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
          echo "result=$OUTPUT" >> $GITHUB_OUTPUT

      - name: Publish a message
        if: always() && contains(steps.diff_result.outputs.result, 'diff')
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2
        with:
          message: |
            ```diff
            ${{ steps.diff_result.outputs.result }}
            ```
